//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Domain.Core.Entities;

namespace Domain.MainModule.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Sucursal))]
    [KnownType(typeof(Contacto))]
    [System.CodeDom.Compiler.GeneratedCode("STE-EF",".NET 4.0")]
    #if !SILVERLIGHT
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage()]
    #endif
    public partial class Agente: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int AgenteID
        {
            get { return _agenteID; }
            set
            {
                if (_agenteID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'AgenteID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _agenteID = value;
                    OnPropertyChanged("AgenteID");
                }
            }
        }
        private int _agenteID;
    
        [DataMember]
        public Nullable<int> SucursalID
        {
            get { return _sucursalID; }
            set
            {
                if (_sucursalID != value)
                {
                    ChangeTracker.RecordOriginalValue("SucursalID", _sucursalID);
                    if (!IsDeserializing)
                    {
                        if (bk_tc_Sucursal != null && bk_tc_Sucursal.SucursalID != value)
                        {
                            bk_tc_Sucursal = null;
                        }
                    }
                    _sucursalID = value;
                    OnPropertyChanged("SucursalID");
                }
            }
        }
        private Nullable<int> _sucursalID;
    
        [DataMember]
        public string nombre
        {
            get { return _nombre; }
            set
            {
                if (_nombre != value)
                {
                    _nombre = value;
                    OnPropertyChanged("nombre");
                }
            }
        }
        private string _nombre;
    
        [DataMember]
        public Nullable<int> SISEcod_agente
        {
            get { return _sISEcod_agente; }
            set
            {
                if (_sISEcod_agente != value)
                {
                    _sISEcod_agente = value;
                    OnPropertyChanged("SISEcod_agente");
                }
            }
        }
        private Nullable<int> _sISEcod_agente;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Sucursal bk_tc_Sucursal
        {
            get { return _bk_tc_Sucursal; }
            set
            {
                if (!ReferenceEquals(_bk_tc_Sucursal, value))
                {
                    var previousValue = _bk_tc_Sucursal;
                    _bk_tc_Sucursal = value;
                    Fixupbk_tc_Sucursal(previousValue);
                    OnNavigationPropertyChanged("bk_tc_Sucursal");
                }
            }
        }
        private Sucursal _bk_tc_Sucursal;
    
        [DataMember]
        public TrackableCollection<Contacto> bk_tc_Contacto
        {
            get
            {
                if (_bk_tc_Contacto == null)
                {
                    _bk_tc_Contacto = new TrackableCollection<Contacto>();
                    _bk_tc_Contacto.CollectionChanged += Fixupbk_tc_Contacto;
                }
                return _bk_tc_Contacto;
            }
            set
            {
                if (!ReferenceEquals(_bk_tc_Contacto, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_bk_tc_Contacto != null)
                    {
                        _bk_tc_Contacto.CollectionChanged -= Fixupbk_tc_Contacto;
                    }
                    _bk_tc_Contacto = value;
                    if (_bk_tc_Contacto != null)
                    {
                        _bk_tc_Contacto.CollectionChanged += Fixupbk_tc_Contacto;
                    }
                    OnNavigationPropertyChanged("bk_tc_Contacto");
                }
            }
        }
        private TrackableCollection<Contacto> _bk_tc_Contacto;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            bk_tc_Sucursal = null;
            bk_tc_Contacto.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void Fixupbk_tc_Sucursal(Sucursal previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.bk_tc_Agente.Contains(this))
            {
                previousValue.bk_tc_Agente.Remove(this);
            }
    
            if (bk_tc_Sucursal != null)
            {
                if (!bk_tc_Sucursal.bk_tc_Agente.Contains(this))
                {
                    bk_tc_Sucursal.bk_tc_Agente.Add(this);
                }
    
                SucursalID = bk_tc_Sucursal.SucursalID;
            }
            else if (!skipKeys)
            {
                SucursalID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("bk_tc_Sucursal")
                    && (ChangeTracker.OriginalValues["bk_tc_Sucursal"] == bk_tc_Sucursal))
                {
                    ChangeTracker.OriginalValues.Remove("bk_tc_Sucursal");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("bk_tc_Sucursal", previousValue);
                }
                if (bk_tc_Sucursal != null && !bk_tc_Sucursal.ChangeTracker.ChangeTrackingEnabled)
                {
                    bk_tc_Sucursal.StartTracking();
                }
            }
        }
    
        private void Fixupbk_tc_Contacto(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Contacto item in e.NewItems)
                {
                    item.bk_tc_Agente = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("bk_tc_Contacto", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Contacto item in e.OldItems)
                {
                    if (ReferenceEquals(item.bk_tc_Agente, this))
                    {
                        item.bk_tc_Agente = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("bk_tc_Contacto", item);
                    }
                }
            }
        }

        #endregion

    }
}
