//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Domain.Core.Entities;

namespace Domain.MainModule.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Estado))]
    [KnownType(typeof(Colonia))]
    [System.CodeDom.Compiler.GeneratedCode("STE-EF",".NET 4.0")]
    #if !SILVERLIGHT
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage()]
    #endif
    public partial class Ciudad: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int CiudadID
        {
            get { return _ciudadID; }
            set
            {
                if (_ciudadID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CiudadID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _ciudadID = value;
                    OnPropertyChanged("CiudadID");
                }
            }
        }
        private int _ciudadID;
    
        [DataMember]
        public Nullable<int> EstadoID
        {
            get { return _estadoID; }
            set
            {
                if (_estadoID != value)
                {
                    ChangeTracker.RecordOriginalValue("EstadoID", _estadoID);
                    if (!IsDeserializing)
                    {
                        if (bk_tc_Estado != null && bk_tc_Estado.EstadoID != value)
                        {
                            bk_tc_Estado = null;
                        }
                    }
                    _estadoID = value;
                    OnPropertyChanged("EstadoID");
                }
            }
        }
        private Nullable<int> _estadoID;
    
        [DataMember]
        public Nullable<int> SISEcod_ciudad
        {
            get { return _sISEcod_ciudad; }
            set
            {
                if (_sISEcod_ciudad != value)
                {
                    _sISEcod_ciudad = value;
                    OnPropertyChanged("SISEcod_ciudad");
                }
            }
        }
        private Nullable<int> _sISEcod_ciudad;
    
        [DataMember]
        public string Descripcion
        {
            get { return _descripcion; }
            set
            {
                if (_descripcion != value)
                {
                    _descripcion = value;
                    OnPropertyChanged("Descripcion");
                }
            }
        }
        private string _descripcion;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Estado bk_tc_Estado
        {
            get { return _bk_tc_Estado; }
            set
            {
                if (!ReferenceEquals(_bk_tc_Estado, value))
                {
                    var previousValue = _bk_tc_Estado;
                    _bk_tc_Estado = value;
                    Fixupbk_tc_Estado(previousValue);
                    OnNavigationPropertyChanged("bk_tc_Estado");
                }
            }
        }
        private Estado _bk_tc_Estado;
    
        [DataMember]
        public TrackableCollection<Colonia> bk_tc_Colonia
        {
            get
            {
                if (_bk_tc_Colonia == null)
                {
                    _bk_tc_Colonia = new TrackableCollection<Colonia>();
                    _bk_tc_Colonia.CollectionChanged += Fixupbk_tc_Colonia;
                }
                return _bk_tc_Colonia;
            }
            set
            {
                if (!ReferenceEquals(_bk_tc_Colonia, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_bk_tc_Colonia != null)
                    {
                        _bk_tc_Colonia.CollectionChanged -= Fixupbk_tc_Colonia;
                    }
                    _bk_tc_Colonia = value;
                    if (_bk_tc_Colonia != null)
                    {
                        _bk_tc_Colonia.CollectionChanged += Fixupbk_tc_Colonia;
                    }
                    OnNavigationPropertyChanged("bk_tc_Colonia");
                }
            }
        }
        private TrackableCollection<Colonia> _bk_tc_Colonia;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            bk_tc_Estado = null;
            bk_tc_Colonia.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void Fixupbk_tc_Estado(Estado previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.bk_tc_Ciudad.Contains(this))
            {
                previousValue.bk_tc_Ciudad.Remove(this);
            }
    
            if (bk_tc_Estado != null)
            {
                if (!bk_tc_Estado.bk_tc_Ciudad.Contains(this))
                {
                    bk_tc_Estado.bk_tc_Ciudad.Add(this);
                }
    
                EstadoID = bk_tc_Estado.EstadoID;
            }
            else if (!skipKeys)
            {
                EstadoID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("bk_tc_Estado")
                    && (ChangeTracker.OriginalValues["bk_tc_Estado"] == bk_tc_Estado))
                {
                    ChangeTracker.OriginalValues.Remove("bk_tc_Estado");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("bk_tc_Estado", previousValue);
                }
                if (bk_tc_Estado != null && !bk_tc_Estado.ChangeTracker.ChangeTrackingEnabled)
                {
                    bk_tc_Estado.StartTracking();
                }
            }
        }
    
        private void Fixupbk_tc_Colonia(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Colonia item in e.NewItems)
                {
                    item.bk_tc_Ciudad = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("bk_tc_Colonia", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Colonia item in e.OldItems)
                {
                    if (ReferenceEquals(item.bk_tc_Ciudad, this))
                    {
                        item.bk_tc_Ciudad = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("bk_tc_Colonia", item);
                    }
                }
            }
        }

        #endregion

    }
}
