//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Domain.Core.Entities;

namespace Domain.MainModule.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(CotizacionCoberturaUbi))]
    [KnownType(typeof(TipoCobertura))]
    [System.CodeDom.Compiler.GeneratedCode("STE-EF",".NET 4.0")]
    #if !SILVERLIGHT
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage()]
    #endif
    public partial class Cobertura: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int CoberturaID
        {
            get { return _coberturaID; }
            set
            {
                if (_coberturaID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CoberturaID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _coberturaID = value;
                    OnPropertyChanged("CoberturaID");
                }
            }
        }
        private int _coberturaID;
    
        [DataMember]
        public Nullable<int> TipoCoberturaID
        {
            get { return _tipoCoberturaID; }
            set
            {
                if (_tipoCoberturaID != value)
                {
                    ChangeTracker.RecordOriginalValue("TipoCoberturaID", _tipoCoberturaID);
                    if (!IsDeserializing)
                    {
                        if (bk_tc_TipoCobertura != null && bk_tc_TipoCobertura.TipoCoberturaID != value)
                        {
                            bk_tc_TipoCobertura = null;
                        }
                    }
                    _tipoCoberturaID = value;
                    OnPropertyChanged("TipoCoberturaID");
                }
            }
        }
        private Nullable<int> _tipoCoberturaID;
    
        [DataMember]
        public string nombre
        {
            get { return _nombre; }
            set
            {
                if (_nombre != value)
                {
                    _nombre = value;
                    OnPropertyChanged("nombre");
                }
            }
        }
        private string _nombre;
    
        [DataMember]
        public Nullable<bool> isPct
        {
            get { return _isPct; }
            set
            {
                if (_isPct != value)
                {
                    _isPct = value;
                    OnPropertyChanged("isPct");
                }
            }
        }
        private Nullable<bool> _isPct;
    
        [DataMember]
        public Nullable<bool> isMes
        {
            get { return _isMes; }
            set
            {
                if (_isMes != value)
                {
                    _isMes = value;
                    OnPropertyChanged("isMes");
                }
            }
        }
        private Nullable<bool> _isMes;
    
        [DataMember]
        public Nullable<bool> isInflacion
        {
            get { return _isInflacion; }
            set
            {
                if (_isInflacion != value)
                {
                    _isInflacion = value;
                    OnPropertyChanged("isInflacion");
                }
            }
        }
        private Nullable<bool> _isInflacion;
    
        [DataMember]
        public Nullable<bool> isNegritaPresentacion
        {
            get { return _isNegritaPresentacion; }
            set
            {
                if (_isNegritaPresentacion != value)
                {
                    _isNegritaPresentacion = value;
                    OnPropertyChanged("isNegritaPresentacion");
                }
            }
        }
        private Nullable<bool> _isNegritaPresentacion;
    
        [DataMember]
        public Nullable<int> ordenPresentacion
        {
            get { return _ordenPresentacion; }
            set
            {
                if (_ordenPresentacion != value)
                {
                    _ordenPresentacion = value;
                    OnPropertyChanged("ordenPresentacion");
                }
            }
        }
        private Nullable<int> _ordenPresentacion;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<CotizacionCoberturaUbi> bk_tr_CotizacionCoberturaUbi
        {
            get
            {
                if (_bk_tr_CotizacionCoberturaUbi == null)
                {
                    _bk_tr_CotizacionCoberturaUbi = new TrackableCollection<CotizacionCoberturaUbi>();
                    _bk_tr_CotizacionCoberturaUbi.CollectionChanged += Fixupbk_tr_CotizacionCoberturaUbi;
                }
                return _bk_tr_CotizacionCoberturaUbi;
            }
            set
            {
                if (!ReferenceEquals(_bk_tr_CotizacionCoberturaUbi, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_bk_tr_CotizacionCoberturaUbi != null)
                    {
                        _bk_tr_CotizacionCoberturaUbi.CollectionChanged -= Fixupbk_tr_CotizacionCoberturaUbi;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (CotizacionCoberturaUbi item in _bk_tr_CotizacionCoberturaUbi)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _bk_tr_CotizacionCoberturaUbi = value;
                    if (_bk_tr_CotizacionCoberturaUbi != null)
                    {
                        _bk_tr_CotizacionCoberturaUbi.CollectionChanged += Fixupbk_tr_CotizacionCoberturaUbi;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (CotizacionCoberturaUbi item in _bk_tr_CotizacionCoberturaUbi)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("bk_tr_CotizacionCoberturaUbi");
                }
            }
        }
        private TrackableCollection<CotizacionCoberturaUbi> _bk_tr_CotizacionCoberturaUbi;
    
        [DataMember]
        public TipoCobertura bk_tc_TipoCobertura
        {
            get { return _bk_tc_TipoCobertura; }
            set
            {
                if (!ReferenceEquals(_bk_tc_TipoCobertura, value))
                {
                    var previousValue = _bk_tc_TipoCobertura;
                    _bk_tc_TipoCobertura = value;
                    Fixupbk_tc_TipoCobertura(previousValue);
                    OnNavigationPropertyChanged("bk_tc_TipoCobertura");
                }
            }
        }
        private TipoCobertura _bk_tc_TipoCobertura;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            bk_tr_CotizacionCoberturaUbi.Clear();
            bk_tc_TipoCobertura = null;
        }

        #endregion

        #region Association Fixup
    
        private void Fixupbk_tc_TipoCobertura(TipoCobertura previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.bk_tc_Cobertura.Contains(this))
            {
                previousValue.bk_tc_Cobertura.Remove(this);
            }
    
            if (bk_tc_TipoCobertura != null)
            {
                if (!bk_tc_TipoCobertura.bk_tc_Cobertura.Contains(this))
                {
                    bk_tc_TipoCobertura.bk_tc_Cobertura.Add(this);
                }
    
                TipoCoberturaID = bk_tc_TipoCobertura.TipoCoberturaID;
            }
            else if (!skipKeys)
            {
                TipoCoberturaID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("bk_tc_TipoCobertura")
                    && (ChangeTracker.OriginalValues["bk_tc_TipoCobertura"] == bk_tc_TipoCobertura))
                {
                    ChangeTracker.OriginalValues.Remove("bk_tc_TipoCobertura");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("bk_tc_TipoCobertura", previousValue);
                }
                if (bk_tc_TipoCobertura != null && !bk_tc_TipoCobertura.ChangeTracker.ChangeTrackingEnabled)
                {
                    bk_tc_TipoCobertura.StartTracking();
                }
            }
        }
    
        private void Fixupbk_tr_CotizacionCoberturaUbi(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (CotizacionCoberturaUbi item in e.NewItems)
                {
                    item.bk_tc_Cobertura = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("bk_tr_CotizacionCoberturaUbi", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CotizacionCoberturaUbi item in e.OldItems)
                {
                    if (ReferenceEquals(item.bk_tc_Cobertura, this))
                    {
                        item.bk_tc_Cobertura = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("bk_tr_CotizacionCoberturaUbi", item);
                        // Delete the dependent end of this identifying association. If the current state is Added,
                        // allow the relationship to be changed without causing the dependent to be deleted.
                        if (item.ChangeTracker.State != ObjectState.Added)
                        {
                            item.MarkAsDeleted();
                        }
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion

    }
}
