//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Domain.Core.Entities;

namespace Domain.MainModule.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Usuario))]
    [KnownType(typeof(Cotizacion))]
    [System.CodeDom.Compiler.GeneratedCode("STE-EF",".NET 4.0")]
    #if !SILVERLIGHT
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage()]
    #endif
    public partial class CotizacionLog: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int CotizacionLogID
        {
            get { return _cotizacionLogID; }
            set
            {
                if (_cotizacionLogID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'CotizacionLogID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _cotizacionLogID = value;
                    OnPropertyChanged("CotizacionLogID");
                }
            }
        }
        private int _cotizacionLogID;
    
        [DataMember]
        public Nullable<int> cotizacionID
        {
            get { return _cotizacionID; }
            set
            {
                if (_cotizacionID != value)
                {
                    ChangeTracker.RecordOriginalValue("cotizacionID", _cotizacionID);
                    if (!IsDeserializing)
                    {
                        if (bk_te_Cotizacion != null && bk_te_Cotizacion.CotizacionID != value)
                        {
                            bk_te_Cotizacion = null;
                        }
                    }
                    _cotizacionID = value;
                    OnPropertyChanged("cotizacionID");
                }
            }
        }
        private Nullable<int> _cotizacionID;
    
        [DataMember]
        public string mensaje
        {
            get { return _mensaje; }
            set
            {
                if (_mensaje != value)
                {
                    _mensaje = value;
                    OnPropertyChanged("mensaje");
                }
            }
        }
        private string _mensaje;
    
        [DataMember]
        public Nullable<int> usuarioID
        {
            get { return _usuarioID; }
            set
            {
                if (_usuarioID != value)
                {
                    ChangeTracker.RecordOriginalValue("usuarioID", _usuarioID);
                    if (!IsDeserializing)
                    {
                        if (bk_tc_Usuario != null && bk_tc_Usuario.UsuarioID != value)
                        {
                            bk_tc_Usuario = null;
                        }
                    }
                    _usuarioID = value;
                    OnPropertyChanged("usuarioID");
                }
            }
        }
        private Nullable<int> _usuarioID;
    
        [DataMember]
        public Nullable<System.DateTime> LogTime
        {
            get { return _logTime; }
            set
            {
                if (_logTime != value)
                {
                    _logTime = value;
                    OnPropertyChanged("LogTime");
                }
            }
        }
        private Nullable<System.DateTime> _logTime;
    
        [DataMember]
        public Nullable<bool> isOK
        {
            get { return _isOK; }
            set
            {
                if (_isOK != value)
                {
                    _isOK = value;
                    OnPropertyChanged("isOK");
                }
            }
        }
        private Nullable<bool> _isOK;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Usuario bk_tc_Usuario
        {
            get { return _bk_tc_Usuario; }
            set
            {
                if (!ReferenceEquals(_bk_tc_Usuario, value))
                {
                    var previousValue = _bk_tc_Usuario;
                    _bk_tc_Usuario = value;
                    Fixupbk_tc_Usuario(previousValue);
                    OnNavigationPropertyChanged("bk_tc_Usuario");
                }
            }
        }
        private Usuario _bk_tc_Usuario;
    
        [DataMember]
        public Cotizacion bk_te_Cotizacion
        {
            get { return _bk_te_Cotizacion; }
            set
            {
                if (!ReferenceEquals(_bk_te_Cotizacion, value))
                {
                    var previousValue = _bk_te_Cotizacion;
                    _bk_te_Cotizacion = value;
                    Fixupbk_te_Cotizacion(previousValue);
                    OnNavigationPropertyChanged("bk_te_Cotizacion");
                }
            }
        }
        private Cotizacion _bk_te_Cotizacion;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            bk_tc_Usuario = null;
            bk_te_Cotizacion = null;
        }

        #endregion

        #region Association Fixup
    
        private void Fixupbk_tc_Usuario(Usuario previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.bk_te_CotizacionLog.Contains(this))
            {
                previousValue.bk_te_CotizacionLog.Remove(this);
            }
    
            if (bk_tc_Usuario != null)
            {
                if (!bk_tc_Usuario.bk_te_CotizacionLog.Contains(this))
                {
                    bk_tc_Usuario.bk_te_CotizacionLog.Add(this);
                }
    
                usuarioID = bk_tc_Usuario.UsuarioID;
            }
            else if (!skipKeys)
            {
                usuarioID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("bk_tc_Usuario")
                    && (ChangeTracker.OriginalValues["bk_tc_Usuario"] == bk_tc_Usuario))
                {
                    ChangeTracker.OriginalValues.Remove("bk_tc_Usuario");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("bk_tc_Usuario", previousValue);
                }
                if (bk_tc_Usuario != null && !bk_tc_Usuario.ChangeTracker.ChangeTrackingEnabled)
                {
                    bk_tc_Usuario.StartTracking();
                }
            }
        }
    
        private void Fixupbk_te_Cotizacion(Cotizacion previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.bk_te_CotizacionLog.Contains(this))
            {
                previousValue.bk_te_CotizacionLog.Remove(this);
            }
    
            if (bk_te_Cotizacion != null)
            {
                if (!bk_te_Cotizacion.bk_te_CotizacionLog.Contains(this))
                {
                    bk_te_Cotizacion.bk_te_CotizacionLog.Add(this);
                }
    
                cotizacionID = bk_te_Cotizacion.CotizacionID;
            }
            else if (!skipKeys)
            {
                cotizacionID = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("bk_te_Cotizacion")
                    && (ChangeTracker.OriginalValues["bk_te_Cotizacion"] == bk_te_Cotizacion))
                {
                    ChangeTracker.OriginalValues.Remove("bk_te_Cotizacion");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("bk_te_Cotizacion", previousValue);
                }
                if (bk_te_Cotizacion != null && !bk_te_Cotizacion.ChangeTracker.ChangeTrackingEnabled)
                {
                    bk_te_Cotizacion.StartTracking();
                }
            }
        }

        #endregion

    }
}
