//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Domain.Core.Entities;

namespace Domain.MainModule.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Asegurado))]
    [System.CodeDom.Compiler.GeneratedCode("STE-EF",".NET 4.0")]
    #if !SILVERLIGHT
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage()]
    #endif
    public partial class TipoTelefono: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int TipoTelefonoID
        {
            get { return _tipoTelefonoID; }
            set
            {
                if (_tipoTelefonoID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'TipoTelefonoID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _tipoTelefonoID = value;
                    OnPropertyChanged("TipoTelefonoID");
                }
            }
        }
        private int _tipoTelefonoID;
    
        [DataMember]
        public Nullable<int> SISEcod_tipo_telef
        {
            get { return _sISEcod_tipo_telef; }
            set
            {
                if (_sISEcod_tipo_telef != value)
                {
                    _sISEcod_tipo_telef = value;
                    OnPropertyChanged("SISEcod_tipo_telef");
                }
            }
        }
        private Nullable<int> _sISEcod_tipo_telef;
    
        [DataMember]
        public string Descripcion
        {
            get { return _descripcion; }
            set
            {
                if (_descripcion != value)
                {
                    _descripcion = value;
                    OnPropertyChanged("Descripcion");
                }
            }
        }
        private string _descripcion;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<Asegurado> bk_tc_Asegurado
        {
            get
            {
                if (_bk_tc_Asegurado == null)
                {
                    _bk_tc_Asegurado = new TrackableCollection<Asegurado>();
                    _bk_tc_Asegurado.CollectionChanged += Fixupbk_tc_Asegurado;
                }
                return _bk_tc_Asegurado;
            }
            set
            {
                if (!ReferenceEquals(_bk_tc_Asegurado, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_bk_tc_Asegurado != null)
                    {
                        _bk_tc_Asegurado.CollectionChanged -= Fixupbk_tc_Asegurado;
                    }
                    _bk_tc_Asegurado = value;
                    if (_bk_tc_Asegurado != null)
                    {
                        _bk_tc_Asegurado.CollectionChanged += Fixupbk_tc_Asegurado;
                    }
                    OnNavigationPropertyChanged("bk_tc_Asegurado");
                }
            }
        }
        private TrackableCollection<Asegurado> _bk_tc_Asegurado;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            bk_tc_Asegurado.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void Fixupbk_tc_Asegurado(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Asegurado item in e.NewItems)
                {
                    item.bk_tc_TipoTelefono = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("bk_tc_Asegurado", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Asegurado item in e.OldItems)
                {
                    if (ReferenceEquals(item.bk_tc_TipoTelefono, this))
                    {
                        item.bk_tc_TipoTelefono = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("bk_tc_Asegurado", item);
                    }
                }
            }
        }

        #endregion

    }
}
