//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Integration.wsSistran {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Asegurado", Namespace="http://schemas.datacontract.org/2004/07/Sistran.Application")]
    [System.SerializableAttribute()]
    public partial class Asegurado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodAsegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodCiudad1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodCiudad2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodColonia1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodColonia2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodConductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodDpto1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodDpto2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodEstCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodFigAsegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodMunicipio1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodMunicipio2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodPais1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodPais2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTipoDir1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTipoDir2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTipoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTipoTelef1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTipoTelef2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescColoniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FecFinCedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FecIniCedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FecNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroExterior1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroExterior2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroInterior1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NroInterior2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumCedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumTarjetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtApellido1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtApellido2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtCalle1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtCalle2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtLugarNacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtNomFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtNombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtSexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtTelef1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TxtTelef2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resErrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string snNewCombField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Agente {
            get {
                return this.AgenteField;
            }
            set {
                if ((object.ReferenceEquals(this.AgenteField, value) != true)) {
                    this.AgenteField = value;
                    this.RaisePropertyChanged("Agente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodAge {
            get {
                return this.CodAgeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodAgeField, value) != true)) {
                    this.CodAgeField = value;
                    this.RaisePropertyChanged("CodAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodAseg {
            get {
                return this.CodAsegField;
            }
            set {
                if ((object.ReferenceEquals(this.CodAsegField, value) != true)) {
                    this.CodAsegField = value;
                    this.RaisePropertyChanged("CodAseg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCiudad1 {
            get {
                return this.CodCiudad1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodCiudad1Field, value) != true)) {
                    this.CodCiudad1Field = value;
                    this.RaisePropertyChanged("CodCiudad1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCiudad2 {
            get {
                return this.CodCiudad2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodCiudad2Field, value) != true)) {
                    this.CodCiudad2Field = value;
                    this.RaisePropertyChanged("CodCiudad2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodColonia1 {
            get {
                return this.CodColonia1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodColonia1Field, value) != true)) {
                    this.CodColonia1Field = value;
                    this.RaisePropertyChanged("CodColonia1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodColonia2 {
            get {
                return this.CodColonia2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodColonia2Field, value) != true)) {
                    this.CodColonia2Field = value;
                    this.RaisePropertyChanged("CodColonia2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodConducto {
            get {
                return this.CodConductoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodConductoField, value) != true)) {
                    this.CodConductoField = value;
                    this.RaisePropertyChanged("CodConducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodDpto1 {
            get {
                return this.CodDpto1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodDpto1Field, value) != true)) {
                    this.CodDpto1Field = value;
                    this.RaisePropertyChanged("CodDpto1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodDpto2 {
            get {
                return this.CodDpto2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodDpto2Field, value) != true)) {
                    this.CodDpto2Field = value;
                    this.RaisePropertyChanged("CodDpto2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodEstCivil {
            get {
                return this.CodEstCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.CodEstCivilField, value) != true)) {
                    this.CodEstCivilField = value;
                    this.RaisePropertyChanged("CodEstCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodFigAseg {
            get {
                return this.CodFigAsegField;
            }
            set {
                if ((object.ReferenceEquals(this.CodFigAsegField, value) != true)) {
                    this.CodFigAsegField = value;
                    this.RaisePropertyChanged("CodFigAseg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodMunicipio1 {
            get {
                return this.CodMunicipio1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodMunicipio1Field, value) != true)) {
                    this.CodMunicipio1Field = value;
                    this.RaisePropertyChanged("CodMunicipio1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodMunicipio2 {
            get {
                return this.CodMunicipio2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodMunicipio2Field, value) != true)) {
                    this.CodMunicipio2Field = value;
                    this.RaisePropertyChanged("CodMunicipio2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodPais1 {
            get {
                return this.CodPais1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodPais1Field, value) != true)) {
                    this.CodPais1Field = value;
                    this.RaisePropertyChanged("CodPais1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodPais2 {
            get {
                return this.CodPais2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodPais2Field, value) != true)) {
                    this.CodPais2Field = value;
                    this.RaisePropertyChanged("CodPais2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTipoDir1 {
            get {
                return this.CodTipoDir1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoDir1Field, value) != true)) {
                    this.CodTipoDir1Field = value;
                    this.RaisePropertyChanged("CodTipoDir1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTipoDir2 {
            get {
                return this.CodTipoDir2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoDir2Field, value) != true)) {
                    this.CodTipoDir2Field = value;
                    this.RaisePropertyChanged("CodTipoDir2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTipoPersona {
            get {
                return this.CodTipoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoPersonaField, value) != true)) {
                    this.CodTipoPersonaField = value;
                    this.RaisePropertyChanged("CodTipoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTipoTelef1 {
            get {
                return this.CodTipoTelef1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoTelef1Field, value) != true)) {
                    this.CodTipoTelef1Field = value;
                    this.RaisePropertyChanged("CodTipoTelef1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTipoTelef2 {
            get {
                return this.CodTipoTelef2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CodTipoTelef2Field, value) != true)) {
                    this.CodTipoTelef2Field = value;
                    this.RaisePropertyChanged("CodTipoTelef2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curp {
            get {
                return this.CurpField;
            }
            set {
                if ((object.ReferenceEquals(this.CurpField, value) != true)) {
                    this.CurpField = value;
                    this.RaisePropertyChanged("Curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescColonia {
            get {
                return this.DescColoniaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescColoniaField, value) != true)) {
                    this.DescColoniaField = value;
                    this.RaisePropertyChanged("DescColonia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FecFinCedula {
            get {
                return this.FecFinCedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.FecFinCedulaField, value) != true)) {
                    this.FecFinCedulaField = value;
                    this.RaisePropertyChanged("FecFinCedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FecIniCedula {
            get {
                return this.FecIniCedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.FecIniCedulaField, value) != true)) {
                    this.FecIniCedulaField = value;
                    this.RaisePropertyChanged("FecIniCedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FecNac {
            get {
                return this.FecNacField;
            }
            set {
                if ((object.ReferenceEquals(this.FecNacField, value) != true)) {
                    this.FecNacField = value;
                    this.RaisePropertyChanged("FecNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroExterior1 {
            get {
                return this.NroExterior1Field;
            }
            set {
                if ((object.ReferenceEquals(this.NroExterior1Field, value) != true)) {
                    this.NroExterior1Field = value;
                    this.RaisePropertyChanged("NroExterior1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroExterior2 {
            get {
                return this.NroExterior2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NroExterior2Field, value) != true)) {
                    this.NroExterior2Field = value;
                    this.RaisePropertyChanged("NroExterior2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroInterior1 {
            get {
                return this.NroInterior1Field;
            }
            set {
                if ((object.ReferenceEquals(this.NroInterior1Field, value) != true)) {
                    this.NroInterior1Field = value;
                    this.RaisePropertyChanged("NroInterior1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroInterior2 {
            get {
                return this.NroInterior2Field;
            }
            set {
                if ((object.ReferenceEquals(this.NroInterior2Field, value) != true)) {
                    this.NroInterior2Field = value;
                    this.RaisePropertyChanged("NroInterior2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumCedula {
            get {
                return this.NumCedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumCedulaField, value) != true)) {
                    this.NumCedulaField = value;
                    this.RaisePropertyChanged("NumCedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumTarjeta {
            get {
                return this.NumTarjetaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumTarjetaField, value) != true)) {
                    this.NumTarjetaField = value;
                    this.RaisePropertyChanged("NumTarjeta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCedula {
            get {
                return this.TipoCedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCedulaField, value) != true)) {
                    this.TipoCedulaField = value;
                    this.RaisePropertyChanged("TipoCedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtApellido1 {
            get {
                return this.TxtApellido1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TxtApellido1Field, value) != true)) {
                    this.TxtApellido1Field = value;
                    this.RaisePropertyChanged("TxtApellido1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtApellido2 {
            get {
                return this.TxtApellido2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TxtApellido2Field, value) != true)) {
                    this.TxtApellido2Field = value;
                    this.RaisePropertyChanged("TxtApellido2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtCalle1 {
            get {
                return this.TxtCalle1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TxtCalle1Field, value) != true)) {
                    this.TxtCalle1Field = value;
                    this.RaisePropertyChanged("TxtCalle1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtCalle2 {
            get {
                return this.TxtCalle2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TxtCalle2Field, value) != true)) {
                    this.TxtCalle2Field = value;
                    this.RaisePropertyChanged("TxtCalle2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtLugarNac {
            get {
                return this.TxtLugarNacField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtLugarNacField, value) != true)) {
                    this.TxtLugarNacField = value;
                    this.RaisePropertyChanged("TxtLugarNac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtNomFactura {
            get {
                return this.TxtNomFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtNomFacturaField, value) != true)) {
                    this.TxtNomFacturaField = value;
                    this.RaisePropertyChanged("TxtNomFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtNombre {
            get {
                return this.TxtNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtNombreField, value) != true)) {
                    this.TxtNombreField = value;
                    this.RaisePropertyChanged("TxtNombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtObservaciones {
            get {
                return this.TxtObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtObservacionesField, value) != true)) {
                    this.TxtObservacionesField = value;
                    this.RaisePropertyChanged("TxtObservaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtSexo {
            get {
                return this.TxtSexoField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtSexoField, value) != true)) {
                    this.TxtSexoField = value;
                    this.RaisePropertyChanged("TxtSexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtTelef1 {
            get {
                return this.TxtTelef1Field;
            }
            set {
                if ((object.ReferenceEquals(this.TxtTelef1Field, value) != true)) {
                    this.TxtTelef1Field = value;
                    this.RaisePropertyChanged("TxtTelef1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TxtTelef2 {
            get {
                return this.TxtTelef2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TxtTelef2Field, value) != true)) {
                    this.TxtTelef2Field = value;
                    this.RaisePropertyChanged("TxtTelef2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resErr {
            get {
                return this.resErrField;
            }
            set {
                if ((object.ReferenceEquals(this.resErrField, value) != true)) {
                    this.resErrField = value;
                    this.RaisePropertyChanged("resErr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string snNewComb {
            get {
                return this.snNewCombField;
            }
            set {
                if ((object.ReferenceEquals(this.snNewCombField, value) != true)) {
                    this.snNewCombField = value;
                    this.RaisePropertyChanged("snNewComb");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Conducto", Namespace="http://schemas.datacontract.org/2004/07/Sistran.Application")]
    [System.SerializableAttribute()]
    public partial class Conducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AAAAMM_TJTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_ASEGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_BANCO_EMIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COD_CONDUCTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IND_CONDUCTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NUM_TJTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RFCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TXT_NOM_PAGADORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TXT_TITULAR_TJTAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AAAAMM_TJTA {
            get {
                return this.AAAAMM_TJTAField;
            }
            set {
                if ((object.ReferenceEquals(this.AAAAMM_TJTAField, value) != true)) {
                    this.AAAAMM_TJTAField = value;
                    this.RaisePropertyChanged("AAAAMM_TJTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_ASEG {
            get {
                return this.COD_ASEGField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_ASEGField, value) != true)) {
                    this.COD_ASEGField = value;
                    this.RaisePropertyChanged("COD_ASEG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_BANCO_EMI {
            get {
                return this.COD_BANCO_EMIField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_BANCO_EMIField, value) != true)) {
                    this.COD_BANCO_EMIField = value;
                    this.RaisePropertyChanged("COD_BANCO_EMI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COD_CONDUCTO {
            get {
                return this.COD_CONDUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.COD_CONDUCTOField, value) != true)) {
                    this.COD_CONDUCTOField = value;
                    this.RaisePropertyChanged("COD_CONDUCTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IND_CONDUCTO {
            get {
                return this.IND_CONDUCTOField;
            }
            set {
                if ((object.ReferenceEquals(this.IND_CONDUCTOField, value) != true)) {
                    this.IND_CONDUCTOField = value;
                    this.RaisePropertyChanged("IND_CONDUCTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUM_TJTA {
            get {
                return this.NUM_TJTAField;
            }
            set {
                if ((object.ReferenceEquals(this.NUM_TJTAField, value) != true)) {
                    this.NUM_TJTAField = value;
                    this.RaisePropertyChanged("NUM_TJTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RFC {
            get {
                return this.RFCField;
            }
            set {
                if ((object.ReferenceEquals(this.RFCField, value) != true)) {
                    this.RFCField = value;
                    this.RaisePropertyChanged("RFC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TXT_NOM_PAGADOR {
            get {
                return this.TXT_NOM_PAGADORField;
            }
            set {
                if ((object.ReferenceEquals(this.TXT_NOM_PAGADORField, value) != true)) {
                    this.TXT_NOM_PAGADORField = value;
                    this.RaisePropertyChanged("TXT_NOM_PAGADOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TXT_TITULAR_TJTA {
            get {
                return this.TXT_TITULAR_TJTAField;
            }
            set {
                if ((object.ReferenceEquals(this.TXT_TITULAR_TJTAField, value) != true)) {
                    this.TXT_TITULAR_TJTAField = value;
                    this.RaisePropertyChanged("TXT_TITULAR_TJTA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSistran.IData")]
    public interface IData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GuardarAsegurados", ReplyAction="http://tempuri.org/IData/GuardarAseguradosResponse")]
        string GuardarAsegurados(System.Collections.Generic.List<Application.Integration.wsSistran.Asegurado> objIntAsegurado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GuardarAsegurados", ReplyAction="http://tempuri.org/IData/GuardarAseguradosResponse")]
        System.Threading.Tasks.Task<string> GuardarAseguradosAsync(System.Collections.Generic.List<Application.Integration.wsSistran.Asegurado> objIntAsegurado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/ConsultaAsegurados", ReplyAction="http://tempuri.org/IData/ConsultaAseguradosResponse")]
        Application.Integration.wsSistran.Asegurado ConsultaAsegurados(string claveRFC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/ConsultaAsegurados", ReplyAction="http://tempuri.org/IData/ConsultaAseguradosResponse")]
        System.Threading.Tasks.Task<Application.Integration.wsSistran.Asegurado> ConsultaAseguradosAsync(string claveRFC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/ConsultaConductos", ReplyAction="http://tempuri.org/IData/ConsultaConductosResponse")]
        System.Collections.Generic.List<Application.Integration.wsSistran.Conducto> ConsultaConductos(string claveRFC, string codAseg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/ConsultaConductos", ReplyAction="http://tempuri.org/IData/ConsultaConductosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Application.Integration.wsSistran.Conducto>> ConsultaConductosAsync(string claveRFC, string codAseg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GuardarConducto", ReplyAction="http://tempuri.org/IData/GuardarConductoResponse")]
        string GuardarConducto(System.Collections.Generic.List<Application.Integration.wsSistran.Conducto> objIntConducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IData/GuardarConducto", ReplyAction="http://tempuri.org/IData/GuardarConductoResponse")]
        System.Threading.Tasks.Task<string> GuardarConductoAsync(System.Collections.Generic.List<Application.Integration.wsSistran.Conducto> objIntConducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataChannel : Application.Integration.wsSistran.IData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataClient : System.ServiceModel.ClientBase<Application.Integration.wsSistran.IData>, Application.Integration.wsSistran.IData {
        
        public DataClient() {
        }
        
        public DataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GuardarAsegurados(System.Collections.Generic.List<Application.Integration.wsSistran.Asegurado> objIntAsegurado) {
            return base.Channel.GuardarAsegurados(objIntAsegurado);
        }
        
        public System.Threading.Tasks.Task<string> GuardarAseguradosAsync(System.Collections.Generic.List<Application.Integration.wsSistran.Asegurado> objIntAsegurado) {
            return base.Channel.GuardarAseguradosAsync(objIntAsegurado);
        }
        
        public Application.Integration.wsSistran.Asegurado ConsultaAsegurados(string claveRFC) {
            return base.Channel.ConsultaAsegurados(claveRFC);
        }
        
        public System.Threading.Tasks.Task<Application.Integration.wsSistran.Asegurado> ConsultaAseguradosAsync(string claveRFC) {
            return base.Channel.ConsultaAseguradosAsync(claveRFC);
        }
        
        public System.Collections.Generic.List<Application.Integration.wsSistran.Conducto> ConsultaConductos(string claveRFC, string codAseg) {
            return base.Channel.ConsultaConductos(claveRFC, codAseg);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Application.Integration.wsSistran.Conducto>> ConsultaConductosAsync(string claveRFC, string codAseg) {
            return base.Channel.ConsultaConductosAsync(claveRFC, codAseg);
        }
        
        public string GuardarConducto(System.Collections.Generic.List<Application.Integration.wsSistran.Conducto> objIntConducto) {
            return base.Channel.GuardarConducto(objIntConducto);
        }
        
        public System.Threading.Tasks.Task<string> GuardarConductoAsync(System.Collections.Generic.List<Application.Integration.wsSistran.Conducto> objIntConducto) {
            return base.Channel.GuardarConductoAsync(objIntConducto);
        }
    }
}
